added helper to render graph.

diff --git a/qgroup_analyzer b/qgroup_analyzer
--- a/qgroup_analyzer
+++ b/qgroup_analyzer
@@ -588,6 +588,25 @@ function wolfram_graph () {
 	} | tr -d '\n' > "$1"
 }
 
+# wolfram_export: export  wolfram graph to image.
+# param:  $1: in-file
+#         $2: out-file
+#         $3: out-image-width
+wolfram_export () {
+
+	[[ -z $2 ]] && echo "usage: wolfram_export <graph_file> <out_file> <out_width>" && return 1
+	[[ ! -e $1 ]] && echo "$1 not found." && return 4
+	[[ -e $2 ]] && echo "$2 already exist" && return 2
+	command -v wolframscript >/dev/null 2>&1 || {
+		echo "wolframscript not found. Mathematica not insatlled?" && return 5
+	}
+	temp="$(mktemp)"
+	echo -n 'Export["'$2'", '$(cat $1)'' | sed -e 's/]$/, ImageSize -> '$3']]/;' | tr -d '\n' > $temp
+	wolframscript -noprompt -script $temp
+	rm $temp
+
+}
+
 [[ ! -z $* ]] && $* || cat << HELP
 usage: $0 <command> <args> [args...]
 
@@ -633,4 +652,12 @@ ADVANCE COMMANDS:
   _get_uin_from_group <gid> <nick/card>
   _if_in_group <gid> <nick/card/uin> <uin?>
   _is_friend <uin>
+
+HELPER COMMANDS:
+  wolfram_export <in_file> <out_file> <img_width>
+    This command export graph generated by 'wolfram_graph' command. <in_file>
+    is the graph to draw, <out_file> is the image to export. should be ends 
+    with pdf/eps/png/tiff, etc. <img_width> specify thw width of image to 
+    export.
+
 HELP
